name: Deploy-prod
'on':
  push:
    branches:
      - second-dev
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2

    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    -
      name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME}}
        password: ${{ secrets.DOCKER_HUB_TOKEN}}
    -
      name: prepare the docker-compose run
      run: |
          ls -l
    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: mikevasaski/234-deploylab-frontend-new:latest
    -
     name: prepare the docker-compose run
     run: |
            mkdir 234-deploylab-frontend-new
            cp docker-compose.yml 234-deploylab-frontend-new/docker-compose.yml
            cd 234-deploylab-frontend-new
            docker-compose -H ${{ secrets.HOST_SERVER }} down
            docker-compose -H ${{ secrets.HOST_SERVER }} pull
            docker-compose -H ${{ secrets.HOST_SERVER }} up -d
            